### ISSUE TITLE
Support for Lambda Layers

### ISSUE THREAD

**Issue by kiernana** [alexa-labs/ask-cli#33]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Support for Lambda Layers in the ask cli deployment configuration to simplify the reuse of common components.

## Expected Behavior

Support for Lambda Layers in the tooling would allow developers to reuse common lambda components, simplifying development and deployment tasks. The lack of such a feature is currently a deciding factor in use of the tooling.

**Comment by RonWang** [comment]
Hey @kiernana 

First thank you for your feature request.
The good news is that: [**ask-cli-x**](https://www.npmjs.com/package/ask-cli-x) is exactly designed to solve your need on AWS Lambda related configurations, because it's using AWS CloudFormation to deploy your Lambda functions. You will be able to modify the skill stack template following the [AWS instruction](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html) to support the LambdaLayer deployment.

More specifically, assuming AlexaSkillFunction is your Lambda function, you will need to create a LayerVersion after you upload your Lambda Layer code into an S3 (Note: make sure the s3 bucket is created in the same region as where this Lambda will be created):
```
AlexaSkillLambdaLayer
  Type: AWS::Lambda::LayerVersion
  Properties:
      CompatibleRuntimes: 
      - nodejs10.x
      - nodejs8.10
      Content: 
        S3Bucket: // put your s3 bucket name
        S3Key: // put your s3 bucket key
        S3ObjectVersion: // put S3 object version if versioning is enabled
      Description: String
      LayerName: String
      LicenseInfo: String

AlexaSkillFunction:
  Type: AWS::Lambda::Function
  Properties: 
    ...
    Layer:
      - !Ref AlexaSkillLambdaLayer
      - // You can reference more then one layer
    ...
```
Let me know if this solves your question!

Thanks,
Ron
